# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Benjamin Rose
email: benjamin.rose@me.com
description: > # this means to ignore newlines until "baseurl:"
  A little corner of the Internet for me. A place to share my thoughts
  about technology, science, and education.
baseurl: "" # the subpath of your site, e.g. /blog, adds everypage after this
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _benjaminrose
github_username:  benjaminrose

# Build settings
markdown: kramdown

# add files that Jekyll wants to ignore
include: [.htaccess]
